### PR TITLE
FOEDAG updates 06-12

### PR DESCRIPTION
**Pull request by ravikiranchollangi**
Show always error message when user try to run some task without project
Update main.yml to use v4.0.0 of setup qt action
Improve create_design tcl command. Close prev design automatically before create new one 
Updates for the file explorer
renamed stars to planning

### CODE REVIEW

**Comment by alaindargelas** [comment]
@ravikiranchollangi this PR breaks some compilation tests

**Comment by ravikiranchollangi** [comment]
> @ravikiranchollangi this PR breaks some compilation tests

Yes, both tests and windows+mac oses Qt issue here like in foedag.

**Comment by ravikiranchollangi** [comment]
> > @ravikiranchollangi this PR breaks some compilation tests
> 
> Yes, both tests and windows+mac oses Qt issue here like in foedag.

the tests are likely coming from this foedag pr change https://github.com/os-fpga/FOEDAG/pull/1617
@KochynVolodymyr @NadeemYaseen FYI

**Comment by alaindargelas** [comment]
@ravikiranchollangi I'm seeing real functional failure:
https://github.com/os-fpga/FOEDAG_rs/actions/runs/9489590064/job/26151213759

**Pull request merged**
