### PR TITLE
Updating FOEDAG for default MUX in RIC

### PR DESCRIPTION
**Pull request by manadher**

### CODE REVIEW

**Comment by ravikiranchollangi** [comment]
macOS gcc is failing already

**Comment by manadher** [comment]
That's a time out related to CI container availability
Look at the next run

**Comment by manadher** [comment]
This looks passing to me :) https://github.com/os-fpga/FOEDAG_rs/actions/runs/8744651139

**Comment by manadher** [comment]
New run succeeded !
BTW The FOEDAG Integration succeeded ...

**Pull request merged**
