### PR TITLE
IPA-FOEDAG_integration

### PR DESCRIPTION
**Pull request by w0lek**

### CODE REVIEW

**Comment by ravikiranchollangi** [comment]
@w0lek I have merged the PR in foedag, you can update this PR now.

**Comment by w0lek** [comment]
@ravikiranchollangi done (this PR is updated to resolve conflict)

**Comment by ravikiranchollangi** [comment]
> @ravikiranchollangi done (this PR is updated to resolve conflict)

I see that the ssh-agent is failing for ubuntu-production, will look into it. 
FYI @NadeemYaseen

**Comment by ravikiranchollangi** [comment]
@w0lek please update the PR since your foedag updates were brought in by #684

**Comment by alaindargelas** [comment]
Merged in #684 #685

**Pull request closed without merging**
